GET http://localhost:8080/employeeHierarchy
Accept: application/json

###
POST http://localhost:8080/employeeHierarchy
Content-Type: application/json

{
  "f": "g",
  "e": "f",
  "b": "c",
  "d": "e",
  "a": "b",
  "c": "d"
}
